// analytics-chatbot-angular/src/app/components/chat-window/chat-window.component.ts
import {
  Component, Input, Output, EventEmitter,
  OnInit, AfterViewChecked, ViewChild, ElementRef
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Message, User, Suggestion, ErrorState } from '../../models/chat.models';
import { SseService } from '../../services/sse.service';
import { AuthService } from '../../services/auth.service';
import { apiUrl, generateSessionId } from '../../services/api.util';
import { MessageBubbleComponent } from '../message-bubble/message-bubble.component';
import { TypingIndicatorComponent } from '../typing-indicator/typing-indicator.component';
import { ErrorBannerComponent } from '../error-banner/error-banner.component';

@Component({
  selector: 'app-chat-window',
  standalone: true,
  imports: [FormsModule, MessageBubbleComponent, TypingIndicatorComponent, ErrorBannerComponent],
  templateUrl: './chat-window.component.html',
  styleUrl:    './chat-window.component.css',
})
export class ChatWindowComponent implements OnInit, AfterViewChecked {
  @Input()  token: string = '';
  @Input()  user: User | null = null;
  @Output() onSignOut = new EventEmitter<void>();

  @ViewChild('messagesEnd') messagesEnd!: ElementRef;
  @ViewChild('inputEl')     inputEl!: ElementRef<HTMLTextAreaElement>;

  messages: Message[]      = [];
  inputText                = '';
  error: ErrorState | null = null;
  waitingForFirst          = false;
  currentId                = '';
  focused                  = false;
  sessionId                = generateSessionId();

  get firstName()  { return this.user?.name?.split(' ')[0] || 'there'; }
  get userInitial(){ return (this.user?.name || this.user?.email || 'U').slice(0,1).toUpperCase(); }
  get pillName()   {
    if (this.user?.name) return this.user.name.split(' ')[0] || this.user.email || 'User';
    return this.user?.email || 'User';
  }

  suggestions: Suggestion[] = [
    { text: 'How many orders were placed last month?',     from: '#6366f1', to: '#8b5cf6' },
    { text: 'What is the revenue trend over time?',         from: '#0891b2', to: '#06b6d4' },
    { text: 'Which traffic source drives the most orders?', from: '#059669', to: '#10b981' },
    { text: 'Show me the top 10 days by order count',       from: '#d97706', to: '#f59e0b' },
  ];

  private shouldScroll = false;

  constructor(public sse: SseService, private auth: AuthService) {}

  ngOnInit(): void {
    if (!this.token) this.token = this.auth.token() || '';
    if (!this.user)  this.user  = this.auth.user();
    setTimeout(() => this.inputEl?.nativeElement.focus(), 100);
  }

  ngAfterViewChecked(): void {
    if (this.shouldScroll) {
      this.messagesEnd?.nativeElement.scrollIntoView({ behavior: 'smooth' });
      this.shouldScroll = false;
    }
  }

  useSuggestion(t: string): void { this.inputText = t; this.inputEl?.nativeElement.focus(); }

  onKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); this.send(); }
  }

  autoResize(e: Event): void {
    const el = e.target as HTMLTextAreaElement;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 120) + 'px';
  }

  async send(): Promise<void> {
    const trimmed = this.inputText.trim();
    if (!trimmed || this.sse.isStreaming()) return;
    this.error = null;

    const userMsg: Message = {
      id:        `user-${Date.now()}`,
      role:      'user',
      content:   trimmed,
      timestamp: new Date(),
    };
    this.messages    = [...this.messages, userMsg];
    this.inputText   = '';
    this.shouldScroll = true;

    const aid = `assistant-${Date.now()}`;
    this.currentId = aid;
    this.messages  = [...this.messages, {
      id:         aid,
      role:       'assistant',
      content:    '',
      timestamp:  new Date(),
      assumptions: [],
      confidence: undefined,
    }];
    this.waitingForFirst = true;

    await this.sse.startStream({
      url:   apiUrl('/chat'),
      body:  { message: trimmed, session_id: this.sessionId },
      token: this.token,

      onChunk: (data) => {

        // ── token: append text content ──────────────────────
        if (data.type === 'token') {
          this.waitingForFirst = false;
          this.messages = this.messages.map(m =>
            m.id === aid ? { ...m, content: m.content + data.content } : m
          );
          this.shouldScroll = true;
        }

        // ── confidence badge ─────────────────────────────────
        else if (data.type === 'confidence') {
          this.messages = this.messages.map(m =>
            m.id === aid
              ? { ...m, confidence: { score: data.score, level: data.level } }
              : m
          );
        }

        // ── assumption flags ─────────────────────────────────
        else if (data.type === 'assumption') {
          this.messages = this.messages.map(m =>
            m.id === aid
              ? { ...m, assumptions: [...(m.assumptions || []), data.text] }
              : m
          );
        }

        // ── chart: backend sends pre-built spec ──────────────
        // If backend sends {"type":"chart","chart":{...spec...}}
        // inject it as a ```chart block so message-bubble can parse it
        else if (data.type === 'chart' && data.chart) {
          const chartBlock = '\n```chart\n' + JSON.stringify(data.chart) + '\n```\n';
          this.messages = this.messages.map(m =>
            m.id === aid ? { ...m, content: m.content + chartBlock } : m
          );
        }
      },

      onError: (err) => {
        this.waitingForFirst = false;
        this.error = err;
        this.messages = this.messages.filter(m => m.id !== aid);
      },

      onDone: () => {
        this.waitingForFirst = false;
        this.shouldScroll    = true;

        // ✅ Force Angular change detection on final message
        // so message-bubble re-runs ngOnChanges with the full content
        // (important: chart JSON is only complete after all tokens arrive)
        this.messages = this.messages.map(m =>
          m.id === aid ? { ...m } : m
        );
      },
    });
  }
}

// frontend/src/components/ChatWindow.jsx
import { useState, useRef, useEffect, useCallback } from 'react'
import { useSSE } from '../hooks/useSSE'
import { apiUrl, generateSessionId } from '../utils/api'
import MessageBubble from './MessageBubble'
import TypingIndicator from './TypingIndicator'
import ErrorBanner from './ErrorBanner'

/**
 * ChatWindow — full-height chat interface with SSE streaming.
 *
 * Props:
 *   - token: Google OAuth JWT credential
 *   - user: { email, name, picture, role, region } from backend/login
 *   - onSignOut: callback to sign out
 */
export default function ChatWindow({ token, user, onSignOut }) {
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [error, setError] = useState(null)
  const [waitingForFirstToken, setWaitingForFirstToken] = useState(false)
  const [sessionId] = useState(() => generateSessionId())
  const messagesEndRef = useRef(null)
  const inputRef = useRef(null)
  const currentAssistantIdRef = useRef(null)
  const { isStreaming, startStream, stopStream } = useSSE()

  const scrollToBottom = useCallback(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [])

  useEffect(() => {
    scrollToBottom()
  }, [messages, waitingForFirstToken, scrollToBottom])

  useEffect(() => {
    inputRef.current?.focus()
  }, [])

  const handleSend = useCallback(async () => {
    const trimmed = input.trim()
    if (!trimmed || isStreaming) return

    setError(null)

    const userMsg = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: trimmed,
    }
    setMessages((prev) => [...prev, userMsg])
    setInput('')

    const assistantId = `assistant-${Date.now()}`
    currentAssistantIdRef.current = assistantId
    const assistantMsg = {
      id: assistantId,
      role: 'assistant',
      content: '',
      assumptions: [],
      confidence: null,
    }
    setMessages((prev) => [...prev, assistantMsg])
    setWaitingForFirstToken(true)

    await startStream({
      url: apiUrl('/chat'),
      body: { message: trimmed, session_id: sessionId },
      token,
      onChunk: (data) => {
        if (data.type === 'token') {
          setWaitingForFirstToken(false)
          setMessages((prev) =>
            prev.map((m) =>
              m.id === assistantId ? { ...m, content: m.content + data.content } : m
            )
          )
        } else if (data.type === 'confidence') {
          setMessages((prev) =>
            prev.map((m) =>
              m.id === assistantId
                ? { ...m, confidence: { score: data.score, level: data.level } }
                : m
            )
          )
        } else if (data.type === 'assumption') {
          setMessages((prev) =>
            prev.map((m) =>
              m.id === assistantId
                ? { ...m, assumptions: [...(m.assumptions || []), data.text] }
                : m
            )
          )
        }
      },
      onError: (err) => {
        setWaitingForFirstToken(false)
        setError(err)
        setMessages((prev) => prev.filter((m) => m.id !== assistantId))
      },
      onDone: () => {
        setWaitingForFirstToken(false)
      },
    })
  }, [input, isStreaming, sessionId, token, startStream])

  const handleKeyDown = useCallback(
    (e) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault()
        handleSend()
      }
    },
    [handleSend]
  )

  return (
    <div className="chat-container bg-gcp-gray-50">
      {/* Header */}
      <header className="chat-header flex items-center gap-2 sm:gap-3 px-3 sm:px-5 py-2.5 sm:py-3 bg-white border-b border-gcp-gray-200 shadow-sm">
        <div className="w-8 h-8 sm:w-9 sm:h-9 shrink-0 rounded-xl bg-gradient-to-br from-gcp-blue to-gcp-blue-dark flex items-center justify-center">
          <svg className="w-4 h-4 sm:w-5 sm:h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
          </svg>
        </div>
        <div className="flex-1 min-w-0">
          <h1 className="text-sm sm:text-base font-semibold text-gcp-gray-900 truncate">
            Analytics Assistant
          </h1>
          <p className="text-[11px] sm:text-xs text-gcp-gray-500 truncate">
            Signed in as {user?.name || user?.email || 'Unknown'}
          </p>
          {(user?.role || user?.region) && (
            <p className="text-[10px] sm:text-[11px] text-gcp-gray-500 truncate">
              Role: <span className="font-medium text-gcp-blue-dark">{user?.role || 'N/A'}</span>
              {user?.region ? ` • ${user.region}` : ''}
            </p>
          )}
        </div>

        {/* User avatar + sign out */}
        <div className="flex items-center gap-1.5 sm:gap-3 shrink-0">
          <span
            className="hidden sm:inline-flex items-center gap-1.5 text-xs text-gcp-green"
            title="Connected"
          >
            <span className="w-2 h-2 bg-gcp-green rounded-full animate-pulse" />
            Connected
          </span>
          <span className="sm:hidden w-2 h-2 bg-gcp-green rounded-full animate-pulse" title="Connected" />
          {user?.picture && (
            <img
              src={user.picture}
              alt={user.name}
              className="w-7 h-7 sm:w-8 sm:h-8 rounded-full border-2 border-gcp-gray-200"
              referrerPolicy="no-referrer"
            />
          )}
          <button
            id="sign-out-button"
            onClick={onSignOut}
            className="text-[11px] sm:text-xs text-gcp-gray-500 hover:text-gcp-red transition-colors px-1.5 sm:px-2 py-1 rounded-lg hover:bg-gcp-red-light whitespace-nowrap"
          >
            Sign out
          </button>
        </div>
      </header>

      {/* Error Banner */}
      <ErrorBanner error={error} onDismiss={() => setError(null)} />

      {/* Messages */}
      <div className="message-area">
        {messages.length === 0 && (
          <div className="flex flex-col items-center justify-center h-full text-center animate-fade-in">
            <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-gcp-blue/10 to-gcp-blue/5 flex items-center justify-center mb-6">
              <svg className="w-10 h-10 text-gcp-blue" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
              </svg>
            </div>
            <h2 className="text-xl font-semibold text-gcp-gray-800 mb-2">
              Hello, {user?.name?.split(' ')[0] || 'there'}! 👋
            </h2>
            <p className="text-sm text-gcp-gray-500 max-w-md mb-8 leading-relaxed">
              Ask me anything about your analytics data. Your access is scoped
              to your role and region.
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-lg w-full">
              {[
                'How many orders were placed last month?',
                'What is the revenue trend over time?',
                'Which traffic source drives the most orders?',
                'Show me the top 10 days by order count',
              ].map((suggestion, i) => (
                <button
                  key={i}
                  id={`suggestion-${i}`}
                  onClick={() => {
                    setInput(suggestion)
                    inputRef.current?.focus()
                  }}
                  className="text-left text-sm px-4 py-3 rounded-xl bg-white border border-gcp-gray-200 text-gcp-gray-600 hover:text-gcp-blue hover:border-gcp-blue/30 hover:bg-gcp-blue-light/50 transition-all duration-200 shadow-sm hover:shadow-md"
                >
                  {suggestion}
                </button>
              ))}
            </div>
          </div>
        )}

        {messages.map((msg) => (
          <MessageBubble key={msg.id} message={msg} />
        ))}

        {waitingForFirstToken && <TypingIndicator />}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Bar */}
      <div className="input-bar">
        <div className="max-w-4xl mx-auto flex items-end gap-2 sm:gap-3">
          <div className="flex-1 min-w-0 relative">
            <textarea
              id="chat-input"
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask about your analytics..."
              rows={1}
              disabled={isStreaming}
              className="w-full min-w-0 resize-none rounded-xl border border-gcp-gray-300 bg-gcp-gray-50 px-3 py-2.5 sm:px-4 sm:py-3 pr-11 sm:pr-12 text-base sm:text-sm text-gcp-gray-900 placeholder:text-gcp-gray-400 focus:outline-none focus:ring-2 focus:ring-gcp-blue/30 focus:border-gcp-blue disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200"
              style={{ maxHeight: '120px' }}
              onInput={(e) => {
                e.target.style.height = 'auto'
                e.target.style.height = Math.min(e.target.scrollHeight, 120) + 'px'
              }}
            />
          </div>

          {isStreaming ? (
            <button
              id="stop-button"
              onClick={stopStream}
              className="flex-shrink-0 w-11 h-11 sm:w-10 sm:h-10 rounded-xl bg-gcp-red text-white flex items-center justify-center hover:bg-red-600 transition-colors shadow-sm touch-manipulation"
              aria-label="Stop streaming"
            >
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <rect x="6" y="6" width="12" height="12" rx="1" />
              </svg>
            </button>
          ) : (
            <button
              id="send-button"
              onClick={handleSend}
              disabled={!input.trim()}
              className="flex-shrink-0 w-11 h-11 sm:w-10 sm:h-10 rounded-xl bg-gcp-blue text-white flex items-center justify-center hover:bg-gcp-blue-dark transition-colors disabled:opacity-40 disabled:cursor-not-allowed shadow-sm touch-manipulation"
              aria-label="Send message"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19V5m0 0l-7 7m7-7l7 7" />
              </svg>
            </button>
          )}
        </div>
        
      </div>
    </div>
  )
}
